pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=bird-grid2
      - status-success=Circle CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge
        strict: true

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
