pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=bird-grid2
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
