pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "status-success=ci/circleci: build"
      - author=bird-grid2
    actions:
      merge:
        strict: "smart"
        method: rebase

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
