version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          PGUSER: root
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: Calmania_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
  
      - ruby/bundle-install      
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load  
      
      - run:
          name: Rubocop
          command: bundle exec rubocop
      
