version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby@3.3.0
        environment:
          BUNDLER_VERSION: 2.5.5
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: Calmania_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://postgres:password@localhost/Calmania_test?sslmode=disable

    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: "Node.js と npm の更新"
          command: |
            curl -sSL "https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v20.11.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash   
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run: echo 'export PYTHON="python3"'
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load  
      
      - run:
          name: Rubocop
          command: bundle exec rubocop -a
      
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
  
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
          
      - add_ssh_keys:
          fingerprints:
            - "21:86:e8:a6:a8:ec:2f:52:da:f9:5c:63:76:86:c7:00"
  
      - deploy:
          name: Capistrano deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            else
              bundle exec cap production deploy
            fi
            